### ISSUE TITLE
update for 8x!

### ISSUE THREAD

**Issue by brunocalado** [jegasus/journal-scaler#3]
Hi. Can you update this module for 8x?

TKS

**Comment by Mattrogers13** [comment]
I would like this option as well. It's great for old eyes like mine.

**Comment by jegasus** [comment]
I believe it's working just fine on version 0.8.x! I was running it in my game and didn't have any issues. If you're having problems, can you be a bit more specific and mention what they are?

**Comment by brunocalado** [comment]
> I believe it's working just fine on version 0.8.x! I was running it in my game and didn't have any issues. If you're having problems, can you be a bit more specific and mention what they are?

Yes. It's working well. Very useful thank you.

I want you to update the   `"compatibleCoreVersion": "0.7.9",`. If you update to v9 you can even use   `"compatibleCoreVersion": "9",`. This will prevent the yellow warning.

**Comment by jegasus** [comment]
I've just released a new version of the module that makes it work for Foundry v9! Please let me know if the issues persist =)

**Comment by brunocalado** [comment]
> I've just released a new version of the module that makes it work for Foundry v9! Please let me know if the issues persist =)

The warning is gone. But, every new foundry v9 build the warning will show again.

Replace  "compatibleCoreVersion": "9.242", by   "compatibleCoreVersion": "9" can remove warnings from all future v9 builds.
