### ISSUE TITLE
Support for V9

### ISSUE THREAD

**Issue by tyler-macinnis** [jegasus/journal-scaler#4]
I'm wondering when this module is going to get support for V9. It currently doesn't work in V9.

**Comment by jegasus** [comment]
Thanks for the report! I'll try to get to this during this weekend!

**Comment by tyler-macinnis** [comment]
This is the exact error that comes up.
![image](https://user-images.githubusercontent.com/21990225/147842162-2c3b9a50-ab4d-46c1-8533-0de32d61f026.png)

**Comment by brunocalado** [comment]
Hi.

Please remove the foundry vtt warning.

Replace "compatibleCoreVersion":"0.9.0" by "compatibleCoreVersion":"9"

Docs: https://gitlab.com/foundrynet/foundryvtt/-/issues/5635

**Comment by jegasus** [comment]
I've just released a new version of the module that makes it work for Foundry v9! Please let me know if the issues persist =)
